load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
  name = "counting-bits",
  hdrs = ["counting-bits.h"],
  visibility = ["//src/test/data-structures-and-algorithms/primitive-types:__pkg__"]
)

cc_library(
  name = "parity",
  hdrs = ["parity.h"],
  visibility = ["//src/test/data-structures-and-algorithms/primitive-types:__pkg__"]
)

cc_library(
  name = "swap-bits",
  hdrs = ["swap-bits.h"],
  visibility = ["//src/test/data-structures-and-algorithms/primitive-types:__pkg__"]
)

cc_library(
  name = "closest-integer-same-weight",
  hdrs = ["closest-integer-same-weight.h"],
  visibility = ["//src/test/data-structures-and-algorithms/primitive-types:__pkg__"]
)
