load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
  name = "counting-bits",
  hdrs = ["counting-bits.h"],
  visibility = ["//src/test/data-structures-and-algorithms/primitive-types:__pkg__"]
)

cc_library(
  name = "parity",
  hdrs = ["parity.h"],
  visibility = ["//src/test/data-structures-and-algorithms/primitive-types:__pkg__"]
)

cc_library(
  name = "swap-bits",
  hdrs = ["swap-bits.h"],
  visibility = ["//src/test/data-structures-and-algorithms/primitive-types:__pkg__"]
)

cc_library(
  name = "closest-integer-same-weight",
  hdrs = ["closest-integer-same-weight.h"],
  visibility = ["//src/test/data-structures-and-algorithms/primitive-types:__pkg__"]
)

cc_library(
  name = "product-without-arithmetical-operators",
  hdrs = ["product-without-arithmetical-operators.h"],
  visibility = ["//src/test/data-structures-and-algorithms/primitive-types:__pkg__"]
)

cc_library(
  name = "quotient-without-arithmetical-operators",
  hdrs = ["quotient-without-arithmetical-operators.h"],
  visibility = ["//src/test/data-structures-and-algorithms/primitive-types:__pkg__"]
)

cc_library(
  name = "compute-pow",
  hdrs = ["compute-pow.h"],
  visibility = ["//src/test/data-structures-and-algorithms/primitive-types:__pkg__"]
)

cc_library(
  name = "reverse-digits",
  hdrs = ["reverse-digits.h"],
  visibility = ["//src/test/data-structures-and-algorithms/primitive-types:__pkg__"]
)
