load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "counting-bits",
    hdrs = ["counting-bits.h"],
    visibility = ["//src/test/data-structures-and-algorithms/primitive-types:__pkg__"]
)
