load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "counting-bits",
#    srcs = ["counting-bits.cc"],
    hdrs = ["counting-bits.h"],
    visibility = ["//test/data-structures-and-algorithms/primitive-types:__pkg__"]
)
