load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
  name = "even-odd",
  hdrs = ["even-odd.h"],
  visibility = ["//src/test/data-structures-and-algorithms/arrays:__pkg__"]
)

cc_library(
  name = "dutch-national-flag",
  hdrs = ["dutch-national-flag.h"],
  visibility = ["//src/test/data-structures-and-algorithms/arrays:__pkg__"]
)

cc_library(
  name = "arbitrary-precision-integer",
  hdrs = ["arbitrary-precision-integer.h"],
  visibility = ["//src/test/data-structures-and-algorithms/arrays:__pkg__"]
)
