cc_test(
  name = "even-odd-test",
  size = "small",
  srcs = ["even-odd-test.cc"],
  deps = ["@gtest//:gtest_main",
          "//src/main/data-structures-and-algorithms/arrays:even-odd"],
)

cc_test(
  name = "dutch-national-flag-test",
  size = "small",
  srcs = ["dutch-national-flag-test.cc"],
  deps = ["@gtest//:gtest_main",
          "//src/main/data-structures-and-algorithms/arrays:dutch-national-flag"],
)

cc_test(
  name = "arbitrary-precision-integer-test",
  size = "small",
  srcs = ["arbitrary-precision-integer-test.cc"],
  deps = ["@gtest//:gtest_main",
          "//src/main/data-structures-and-algorithms/arrays:arbitrary-precision-integer"],
)

