cc_test(
  name = "counting-bits-test",
  size = "small",
  srcs = ["counting-bits-test.cc"],
  deps = ["@gtest//:gtest_main",
          "//src/main/data-structures-and-algorithms/primitive-types:counting-bits"],
)
