cc_test(
  name = "counting-bits-test",
  size = "small",
  srcs = ["counting-bits-test.cc"],
  deps = ["@gtest//:gtest_main",
          "//src/main/data-structures-and-algorithms/primitive-types:counting-bits"],
)

cc_test(
  name = "parity-test",
  size = "small",
  srcs = ["parity-test.cc"],
  deps = ["@gtest//:gtest_main",
          "//src/main/data-structures-and-algorithms/primitive-types:parity"],
)

cc_test(
  name = "swap-bits-test",
  size = "small",
  srcs = ["swap-bits-test.cc"],
  deps = ["@gtest//:gtest_main",
          "//src/main/data-structures-and-algorithms/primitive-types:swap-bits"],
)

cc_test(
  name = "closest-integer-same-weight-test",
  size = "small",
  srcs = ["closest-integer-same-weight-test.cc"],
  deps = ["@gtest//:gtest_main",
          "//src/main/data-structures-and-algorithms/primitive-types:closest-integer-same-weight"],
)

cc_test(
  name = "product-without-arithmetical-operators-test",
  size = "small",
  srcs = ["product-without-arithmetical-operators-test.cc"],
  deps = ["@gtest//:gtest_main",
          "//src/main/data-structures-and-algorithms/primitive-types:product-without-arithmetical-operators"],
)

cc_test(
  name = "quotient-without-arithmetical-operators-test",
  size = "small",
  srcs = ["quotient-without-arithmetical-operators-test.cc"],
  deps = ["@gtest//:gtest_main",
          "//src/main/data-structures-and-algorithms/primitive-types:quotient-without-arithmetical-operators"],
)

cc_test(
  name = "compute-pow-test",
  size = "small",
  srcs = ["compute-pow-test.cc"],
  deps = ["@gtest//:gtest_main",
          "//src/main/data-structures-and-algorithms/primitive-types:compute-pow"],
)
