load("@rules_clojure//:rules.bzl", "clojure_library")

clojure_library(
  name = "counting-bits",
  srcs = ["counting-bits.clj"],
  visibility = ["//src/test/clj/data-structures-and-algorithms/primitive-types:__pkg__"]
)
