load("@rules_clojure//:rules.bzl", "clojure_test")

clojure_test(
  name = "counting-bits-test",
  srcs = ["counting-bits-test.clj"],
  deps = ["//src/main/clj/data-structures-and-algorithms/primitive-types:counting-bits"]
)
