java_test(
  name = "PrimitiveTypesTests",
  srcs = [
    "PrimitiveTypesTests.java", # suite
    "CountingBitsTest.java"],
  deps = ["//src/main/java/datastructuresandalgorithms/primitivetypes:CountingBits"]
)
